{
 "title": "GraphDB",
 "description": "Grafana dashboard for monitoring GraphDB. Connects to Prometheus that scrapes GraphDB.",
 "tags": [ "GraphDB" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "description": "Global page cache hits",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "graphdb_cache_hit{instance=\"graphdb:7200\", job=\"GraphDB Data Structures Metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "timeseries",
   "description": "Global cache misses",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "graphdb_cache_miss{instance=\"graphdb:7200\", job=\"GraphDB Data Structures Metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Class Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "graphdb_class_count{instance=\"graphdb:7200\", job=\"GraphDB Infrastructure Metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maximum Memory Available",
   "type": "timeseries",
   "description": "Maximum amount of memory available to the GraphDB instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "graphdb_heap_max_mem{instance=\"graphdb:7200\", job=\"GraphDB Infrastructure Metrics\"}/1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Heap Memory",
   "type": "timeseries",
   "description": "Amount of memory used by GraphDB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "graphdb_heap_used_mem{instance=\"graphdb:7200\", job=\"GraphDB Infrastructure Metrics\"}/1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Off Heap Committed Memory",
   "type": "timeseries",
   "description": "Current off heap committed memory in MB ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "graphdb_nonheap_committed_mem{instance=\"graphdb:7200\", job=\"GraphDB Infrastructure Metrics\"}/1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Memory in Use",
   "type": "timeseries",
   "description": "Current committed memory in MB ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "graphdb_heap_committed_mem{instance=\"graphdb:7200\", job=\"GraphDB Infrastructure Metrics\"}/1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Off Heap Used Memory",
   "type": "timeseries",
   "description": "Current off heap used memory in MB ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "graphdb_nonheap_used_mem{instance=\"graphdb:7200\", job=\"GraphDB Infrastructure Metrics\"}/1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "description": "Current CPU load for the entire system",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "graphdb_cpu_load{instance=\"graphdb:7200\", job=\"GraphDB Infrastructure Metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "The number of file descriptors open",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "graphdb_open_file_descriptors{instance=\"graphdb:7200\", job=\"GraphDB Infrastructure Metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Logs Partition Free Space",
   "type": "timeseries",
   "description": "The amount of free space in the partition where the logs are stored",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "graphdb_logs_dir_free{instance=\"graphdb:7200\", job=\"GraphDB Infrastructure Metrics\"}/1e9\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs Partition Used Space",
   "type": "timeseries",
   "description": "The amount of storage used in the partition where the logs are stored",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "graphdb_logs_dir_used{instance=\"graphdb:7200\", job=\"GraphDB Infrastructure Metrics\"}/1e9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Directory Used Space",
   "type": "timeseries",
   "description": "Used storage space on the partition where the data directory sits, in GB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "graphdb_data_dir_used{instance=\"graphdb:7200\", job=\"GraphDB Infrastructure Metrics\"}/1e+9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Directory Free Space",
   "type": "timeseries",
   "description": "Free storage space on the partition where the data directory sits, in GB\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "graphdb_data_dir_free{instance=\"graphdb:7200\", job=\"GraphDB Infrastructure Metrics\"}/1e+6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work Directory Free Space",
   "type": "timeseries",
   "description": "Free storage space on the partition where the work directory sits, in GB\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "graphdb_work_dir_free{instance=\"graphdb:7200\", job=\"GraphDB Infrastructure Metrics\"}/1e+9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work Directory Used Space",
   "type": "timeseries",
   "description": "Free storage space on the partition where the work directory sits, in GB\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "graphdb_work_dir_used{instance=\"graphdb:7200\", job=\"GraphDB Infrastructure Metrics\"}/1e+9",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}